apiVersion: v1
kind: Service
metadata:
  name: public-frontend
  namespace: frontend
spec:
  type: NodePort
  selector: 
    tier: frontend
  ports: 
    - port: 80
      targetPort: 80
      nodePort: 30008

